include:
  - project: 'belux-vacc/belux-discord-bot-ci'
    ref: main
    file: '/deploy.yml'

stages:
  - build
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID
  LATEST: $CI_REGISTRY_IMAGE:latest

docker-build:
  only:
    refs:
      - main
      - develop
  stage: build
  image: docker:$CI_DOCKER_VERSION
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  # The purpose of the latest tag is simply to speed up builds.
  script:
    - docker pull $LATEST || true
    - docker build -t $IMAGE_TAG .
    - docker tag $IMAGE_TAG $LATEST
    - docker push $IMAGE_TAG
    - docker push $LATEST
