name: Push to GitLab

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'main'
        fetch-depth: 0
        fetch-tags: 1
    - name: Push to GitLab
      run: |
        git checkout main
        git push --set-upstream https://Epse:${{ secrets.GITLAB_PA }}@gitlab.com/belux-vacc/belux-discord-bot.git main
