name: PR Test Build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22.4.x
    - name: Install dependencies
      run: npm ci --include dev
    - name: Build
      run: npx tsup src/server.ts src/deploy-commands.ts --minify
